# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'soqqle' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for soqqle
    rn_maps_path = '../node_modules/react-native-maps'
      inherit! :search_paths
      pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge', # Include this for RN >= 0.47
        'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
        'cxxreact',
        'RCTAnimation', # Needed for FlatList and animations running on native UI thread
        'RCTBlob',
        #'RCTPushNotification', # Needed if using push notification
        'RCTActionSheet', # Needed for specific use cases
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket', # Needed for debugging
        # Add any other subspecs you want to use in your project
        ]
        # Explicitly include Yoga if you are using RN >= 0.42.0
        pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

        # Third party deps podspec link
        pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
        pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
        pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

        pod 'AccountKit'
    
        pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

      pod 'react-native-video', :path => '../node_modules/react-native-video'

      pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

      pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end
