export const STORIES_LIST_API = 'https://stgapi.soqqle.com/storiesGetAll';
export const STORY_HAS_VIDEO_API = 'https://stgapi.soqqle.com/story/{}/has-video';
export const AGENDA_LIST_API = 'https://stgapi.soqqle.com/taskgroupGetAll?page={}';
export const USER_TASK_GROUP_LIST_API = 'https://stgapi.soqqle.com/userTaskGroup?page={page}&type={type}';
export const SAVE_USER_TASK_GROUP_API = 'https://stgapi.soqqle.com/saveTaskGroup';
export const USER_TASK_GROUP_LIST_PATH_API = 'userTaskGroup?page={page}&type={type}';
export const TEAM_UPDATE_API = 'https://stgapi.soqqle.com/team/{}/';
export const ACHIEVEMENT_LIST_PATH_API = '/achievement/group/';
export const USER_ACHIEVEMENT_LIST_PATH_API = '/userAchievement/{}/'
export const USER_SPARK_LIST_PATH_API = '/userAccounting?id={}'
export const SAVE_ANSWERS_PATH_API = '/hangoutAnswersSave';
export const SAVE_TASK_PATH_API = '/taskSavePost';
export const UPDATE_USER_TASK_GROUP_API_PATH = '/taskGroup/{}';
export const GET_OBJECTIVE_API_PATH = '/taskRefs/{}';
export const GET_MESSAGE_LIST_API = '/fetchConversationByParticipants?chatType=GROUP&ids={team_id}';
export const CHAT_SOCKET_URL = 'stgapi.soqqle.com';
export const STORY_CHALLENGES_LIST_API_PATH = '/challengeStory';
